global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: [ 'localhost:9090' ]
  - job_name: 'otel.collector.exporter'
    static_configs:
      - targets: [ 'otel.collector:8889' ]
#  - job_name: 'otel.collector.self'
#    static_configs:
#      - targets: [ 'otel.collector:8888' ]
  - job_name: 'grafana.tempo'
    static_configs:
      - targets: [ 'grafana.tempo:3200' ]